ERROR - 2023-01-30 21:00:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php:174
Stack trace:
#0 /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php(174): mysqli->real_connect()
#1 /home/adriano/php/escritorio/system/Database/BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/adriano/php/escritorio/system/Database/BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/adriano/php/escritorio/system/Database/BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query()
#4 /home/adriano/php/escritorio/system/Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 /home/adriano/php/escritorio/system/BaseModel.php(618): CodeIgniter\Model->doFindAll()
#6 /home/adriano/php/escritorio/app/Controllers/Client.php(15): CodeIgniter\BaseModel->findAll()
#7 /home/adriano/php/escritorio/system/CodeIgniter.php(934): App\Controllers\Client->index()
#8 /home/adriano/php/escritorio/system/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController()
#9 /home/adriano/php/escritorio/system/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest()
#10 /home/adriano/php/escritorio/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 /home/adriano/php/escritorio/system/Commands/Server/rewrite.php(47): require_once('...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php:218
Stack trace:
#0 /home/adriano/php/escritorio/system/Database/BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/adriano/php/escritorio/system/Database/BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/adriano/php/escritorio/system/Database/BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query()
#3 /home/adriano/php/escritorio/system/Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#4 /home/adriano/php/escritorio/system/BaseModel.php(618): CodeIgniter\Model->doFindAll()
#5 /home/adriano/php/escritorio/app/Controllers/Client.php(15): CodeIgniter\BaseModel->findAll()
#6 /home/adriano/php/escritorio/system/CodeIgniter.php(934): App\Controllers\Client->index()
#7 /home/adriano/php/escritorio/system/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController()
#8 /home/adriano/php/escritorio/system/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest()
#9 /home/adriano/php/escritorio/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 /home/adriano/php/escritorio/system/Commands/Server/rewrite.php(47): require_once('...')
#11 {main}
CRITICAL - 2023-01-30 21:00:40 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 427.
 1 SYSTEMPATH/Database/BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH/Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(618): CodeIgniter\Model->doFindAll()
 5 APPPATH/Controllers/Client.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(934): App\Controllers\Client->index()
 7 SYSTEMPATH/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController()
 8 SYSTEMPATH/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest()
 9 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-30 21:01:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php:174
Stack trace:
#0 /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php(174): mysqli->real_connect()
#1 /home/adriano/php/escritorio/system/Database/BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/adriano/php/escritorio/system/Database/BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/adriano/php/escritorio/system/Database/BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query()
#4 /home/adriano/php/escritorio/system/Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 /home/adriano/php/escritorio/system/BaseModel.php(618): CodeIgniter\Model->doFindAll()
#6 /home/adriano/php/escritorio/app/Controllers/Client.php(15): CodeIgniter\BaseModel->findAll()
#7 /home/adriano/php/escritorio/system/CodeIgniter.php(934): App\Controllers\Client->index()
#8 /home/adriano/php/escritorio/system/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController()
#9 /home/adriano/php/escritorio/system/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest()
#10 /home/adriano/php/escritorio/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 /home/adriano/php/escritorio/system/Commands/Server/rewrite.php(47): require_once('...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php:218
Stack trace:
#0 /home/adriano/php/escritorio/system/Database/BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/adriano/php/escritorio/system/Database/BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/adriano/php/escritorio/system/Database/BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query()
#3 /home/adriano/php/escritorio/system/Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#4 /home/adriano/php/escritorio/system/BaseModel.php(618): CodeIgniter\Model->doFindAll()
#5 /home/adriano/php/escritorio/app/Controllers/Client.php(15): CodeIgniter\BaseModel->findAll()
#6 /home/adriano/php/escritorio/system/CodeIgniter.php(934): App\Controllers\Client->index()
#7 /home/adriano/php/escritorio/system/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController()
#8 /home/adriano/php/escritorio/system/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest()
#9 /home/adriano/php/escritorio/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 /home/adriano/php/escritorio/system/Commands/Server/rewrite.php(47): require_once('...')
#11 {main}
CRITICAL - 2023-01-30 21:01:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 427.
 1 SYSTEMPATH/Database/BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH/Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(618): CodeIgniter\Model->doFindAll()
 5 APPPATH/Controllers/Client.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(934): App\Controllers\Client->index()
 7 SYSTEMPATH/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController()
 8 SYSTEMPATH/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest()
 9 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-30 21:02:44 --> mysqli_sql_exception: Table 'php01.clients' doesn't exist in /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php:295
Stack trace:
#0 /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php(295): mysqli->query()
#1 /home/adriano/php/escritorio/system/Database/BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute()
#2 /home/adriano/php/escritorio/system/Database/BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery()
#3 /home/adriano/php/escritorio/system/Database/BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query()
#4 /home/adriano/php/escritorio/system/Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 /home/adriano/php/escritorio/system/BaseModel.php(618): CodeIgniter\Model->doFindAll()
#6 /home/adriano/php/escritorio/app/Controllers/Client.php(15): CodeIgniter\BaseModel->findAll()
#7 /home/adriano/php/escritorio/system/CodeIgniter.php(934): App\Controllers\Client->index()
#8 /home/adriano/php/escritorio/system/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController()
#9 /home/adriano/php/escritorio/system/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest()
#10 /home/adriano/php/escritorio/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 /home/adriano/php/escritorio/system/Commands/Server/rewrite.php(47): require_once('...')
#12 {main}
CRITICAL - 2023-01-30 21:02:44 --> Table 'php01.clients' doesn't exist
in SYSTEMPATH/Database/BaseConnection.php on line 645.
 1 SYSTEMPATH/Database/BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query()
 2 SYSTEMPATH/Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH/BaseModel.php(618): CodeIgniter\Model->doFindAll()
 4 APPPATH/Controllers/Client.php(15): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH/CodeIgniter.php(934): App\Controllers\Client->index()
 6 SYSTEMPATH/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController()
 7 SYSTEMPATH/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-30 21:02:49 --> mysqli_sql_exception: Table 'php01.clients' doesn't exist in /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php:295
Stack trace:
#0 /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php(295): mysqli->query()
#1 /home/adriano/php/escritorio/system/Database/BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute()
#2 /home/adriano/php/escritorio/system/Database/BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery()
#3 /home/adriano/php/escritorio/system/Database/BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query()
#4 /home/adriano/php/escritorio/system/Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 /home/adriano/php/escritorio/system/BaseModel.php(618): CodeIgniter\Model->doFindAll()
#6 /home/adriano/php/escritorio/app/Controllers/Client.php(15): CodeIgniter\BaseModel->findAll()
#7 /home/adriano/php/escritorio/system/CodeIgniter.php(934): App\Controllers\Client->index()
#8 /home/adriano/php/escritorio/system/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController()
#9 /home/adriano/php/escritorio/system/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest()
#10 /home/adriano/php/escritorio/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 /home/adriano/php/escritorio/system/Commands/Server/rewrite.php(47): require_once('...')
#12 {main}
CRITICAL - 2023-01-30 21:02:49 --> Table 'php01.clients' doesn't exist
in SYSTEMPATH/Database/BaseConnection.php on line 645.
 1 SYSTEMPATH/Database/BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query()
 2 SYSTEMPATH/Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH/BaseModel.php(618): CodeIgniter\Model->doFindAll()
 4 APPPATH/Controllers/Client.php(15): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH/CodeIgniter.php(934): App\Controllers\Client->index()
 6 SYSTEMPATH/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController()
 7 SYSTEMPATH/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-30 21:06:34 --> mysqli_sql_exception: INSERT command denied to user 'adriano'@'localhost' for table 'migrations' in /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php:295
Stack trace:
#0 /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php(295): mysqli->query()
#1 /home/adriano/php/escritorio/system/Database/BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute()
#2 /home/adriano/php/escritorio/system/Database/BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery()
#3 /home/adriano/php/escritorio/system/Database/BaseBuilder.php(2295): CodeIgniter\Database\BaseConnection->query()
#4 /home/adriano/php/escritorio/system/Database/MigrationRunner.php(609): CodeIgniter\Database\BaseBuilder->insert()
#5 /home/adriano/php/escritorio/system/Database/MigrationRunner.php(195): CodeIgniter\Database\MigrationRunner->addHistory()
#6 /home/adriano/php/escritorio/system/Commands/Database/Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest()
#7 /home/adriano/php/escritorio/system/CLI/Commands.php(65): CodeIgniter\Commands\Database\Migrate->run()
#8 /home/adriano/php/escritorio/system/CLI/Console.php(37): CodeIgniter\CLI\Commands->run()
#9 /home/adriano/php/escritorio/spark(97): CodeIgniter\CLI\Console->run()
#10 {main}
ERROR - 2023-01-30 21:07:00 --> mysqli_sql_exception: INSERT command denied to user 'adriano'@'localhost' for table 'migrations' in /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php:295
Stack trace:
#0 /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php(295): mysqli->query()
#1 /home/adriano/php/escritorio/system/Database/BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute()
#2 /home/adriano/php/escritorio/system/Database/BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery()
#3 /home/adriano/php/escritorio/system/Database/BaseBuilder.php(2295): CodeIgniter\Database\BaseConnection->query()
#4 /home/adriano/php/escritorio/system/Database/MigrationRunner.php(609): CodeIgniter\Database\BaseBuilder->insert()
#5 /home/adriano/php/escritorio/system/Database/MigrationRunner.php(195): CodeIgniter\Database\MigrationRunner->addHistory()
#6 /home/adriano/php/escritorio/system/Commands/Database/Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest()
#7 /home/adriano/php/escritorio/system/CLI/Commands.php(65): CodeIgniter\Commands\Database\Migrate->run()
#8 /home/adriano/php/escritorio/system/CLI/Console.php(37): CodeIgniter\CLI\Commands->run()
#9 /home/adriano/php/escritorio/spark(97): CodeIgniter\CLI\Console->run()
#10 {main}
ERROR - 2023-01-30 21:11:22 --> mysqli_sql_exception: Unknown table 'php01.clients' in /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php:295
Stack trace:
#0 /home/adriano/php/escritorio/system/Database/MySQLi/Connection.php(295): mysqli->query()
#1 /home/adriano/php/escritorio/system/Database/BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute()
#2 /home/adriano/php/escritorio/system/Database/BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery()
#3 /home/adriano/php/escritorio/system/Database/Forge.php(637): CodeIgniter\Database\BaseConnection->query()
#4 /home/adriano/php/escritorio/app/Database/Migrations/2023-01-30-205235_ClientCreate.php(33): CodeIgniter\Database\Forge->dropTable()
#5 /home/adriano/php/escritorio/system/Database/MigrationRunner.php(877): App\Database\Migrations\ClientCreate->down()
#6 /home/adriano/php/escritorio/system/Database/MigrationRunner.php(299): CodeIgniter\Database\MigrationRunner->migrate()
#7 /home/adriano/php/escritorio/system/Commands/Database/MigrateRollback.php(92): CodeIgniter\Database\MigrationRunner->regress()
#8 /home/adriano/php/escritorio/system/CLI/Commands.php(65): CodeIgniter\Commands\Database\MigrateRollback->run()
#9 /home/adriano/php/escritorio/system/CLI/BaseCommand.php(114): CodeIgniter\CLI\Commands->run()
#10 /home/adriano/php/escritorio/system/Commands/Database/MigrateRefresh.php(84): CodeIgniter\CLI\BaseCommand->call()
#11 /home/adriano/php/escritorio/system/CLI/Commands.php(65): CodeIgniter\Commands\Database\MigrateRefresh->run()
#12 /home/adriano/php/escritorio/system/CLI/Console.php(37): CodeIgniter\CLI\Commands->run()
#13 /home/adriano/php/escritorio/spark(97): CodeIgniter\CLI\Console->run()
#14 {main}
